//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace purchase_sale_storeroom
{
    public partial class HGuidanceCardBrowse
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        protected global::System.Web.UI.WebControls.Repeater Rpt_Languages;
        protected global::System.Web.UI.WebControls.Panel Pnl_Empty;
        protected global::System.Web.UI.WebControls.Repeater Rpt_Cards;
    }
}
