//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace purchase_sale_storeroom
{
    public partial class System_HGuidanceCardUpload
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        protected global::System.Web.UI.WebControls.HyperLink Lnk_Browse;
        protected global::System.Web.UI.WebControls.Panel Pnl_Message;
        protected global::System.Web.UI.WebControls.Literal Lit_Message;
        protected global::System.Web.UI.WebControls.Literal Lit_FormTitle;
        protected global::System.Web.UI.WebControls.HiddenField Hf_TopicID;
        protected global::System.Web.UI.WebControls.Label Lbl_TopicDate;
        protected global::System.Web.UI.WebControls.TextBox Txt_TopicDate;
        protected global::System.Web.UI.WebControls.Label Lbl_TopicTitle;
        protected global::System.Web.UI.WebControls.TextBox Txt_TopicTitle;
        protected global::System.Web.UI.WebControls.Label Lbl_Description;
        protected global::System.Web.UI.WebControls.TextBox Txt_Description;
        protected global::System.Web.UI.WebControls.CheckBox Chk_IsPublished;
        protected global::System.Web.UI.WebControls.FileUpload Fu_ZhTW;
        protected global::System.Web.UI.WebControls.Literal Lit_CurrentZhTW;
        protected global::System.Web.UI.WebControls.FileUpload Fu_En;
        protected global::System.Web.UI.WebControls.Literal Lit_CurrentEn;
        protected global::System.Web.UI.WebControls.FileUpload Fu_Id;
        protected global::System.Web.UI.WebControls.Literal Lit_CurrentId;
        protected global::System.Web.UI.WebControls.FileUpload Fu_ZhCN;
        protected global::System.Web.UI.WebControls.Literal Lit_CurrentZhCN;
        protected global::System.Web.UI.WebControls.Button Btn_Save;
        protected global::System.Web.UI.WebControls.HyperLink Lnk_New;
        protected global::System.Web.UI.WebControls.GridView Gv_Recent;
    }
}
